export const stepWords = [
    {
      title: "이름을 입력해주세요",
      subTitle: "자격증 검증을 위한 본인인증 시 정확한 이름이 필요해요",
      label: "이름",
      placeholder: "이름을 입력해주세요",
      regex: /^[a-zA-Z가-힣\s]{2,}$/,
      errorMessage: "올바른 이름을 입력해주세요",
      key: "name",
    },
    {
      title: "이메일을 설정해주세요",
      subTitle: "자격증 검토 결과는 입력하신 이메일로 발송되니, 정확한 이메일을 입력해주세요",
      label: "이메일",
      placeholder: "이메일을 입력해주세요",
      regex: /^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
      errorMessage: "올바른 이메일을 입력해주세요",
      key: "email",
    },
    {
      title: "휴대폰 번호를 입력해주세요",
      subTitle: "입력하신 번호로 중요한 알림을 보내드려요",
      label: "휴대폰 번호",
      placeholder: "휴대폰 번호를 입력해주세요",
      regex: /^01[0-9]-\d{3,4}-\d{4}$/,
      errorMessage: "올바른 휴대폰 번호를 입력해주세요",
      key: "phone",
    },
    {
      title: "닉네임을 설정해주세요",
      subTitle: "",
      label: "닉네임",
      placeholder: "닉네임을 설정해주세요",
      regex: /^[a-zA-Z가-힣0-9]{2,10}$/,
      errorMessage: "올바른 닉네임을 입력해주세요 (2~10자)",
      suffixButton: "중복 검사",
      key: "nickname",
    },
  ];